feature
TeodorTeaca/AngularMovies pull request #1
Opened 2020-08-18 15:17 UTC by TeodorTeaca

2020-08-19 06:28 UTC, chitanumihai requested changes
fix the comments

2020-08-19 06:28 UTC, chitanumihai commented on src/app/list.movies/list.movies.component.html
> +        <img src="http://image.tmdb.org/t/p/original/{{poster.posterPath}}" />
refactor, map the object in the service

2020-08-19 06:28 UTC, chitanumihai commented on src/app/list.movies/list.movies.component.html
> +        <img src="http://image.tmdb.org/t/p/original/{{poster.posterPath}}" />
rename the file movie-list.component.html

2020-08-19 06:28 UTC, chitanumihai commented on src/app/list.movies/list.movies.component.ts
> +  public posters: object[];
add interface

2020-08-19 06:28 UTC, chitanumihai commented on src/app/list.movies/list.movies.component.ts
> +  public posters: object[];
or type

2020-08-19 06:28 UTC, chitanumihai commented on src/app/list.movies/list.movies.component.ts
> +      .subscribe((posters) => {
handle error

2020-08-19 06:28 UTC, chitanumihai commented on src/app/services/movies.service.ts
> +        return this.http.get(`https://api.themoviedb.org/3/movie/${endPoint}?api_key=8673e8c11eae0b8c433a41602fd2ddfc`)
implement http interceptor, and extract url as const

2020-08-19 06:28 UTC, chitanumihai commented on src/app/services/movies.service.ts
> +            .pipe(map((res: any) => res.results.map((movie: any) => ({ posterPath: `${movie.poster_path}` }))))
implement interface

2020-08-19 06:28 UTC, chitanumihai commented on src/index.html
> +  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
this can be implemented in angular.json file

2020-08-20 06:27 UTC, chitanumihai requested changes

2020-08-20 06:27 UTC, chitanumihai commented on src/app/list.movies/list-movies.component.ts
> +  public error: boolean = null;
????

2020-08-20 06:27 UTC, chitanumihai commented on src/app/list.movies/list-movies.component.ts
> +  private request: Subscription;
declarations are always before the constructor

2020-08-20 06:28 UTC, vadimb commented on src/app/list.movies/list-movies.component.ts
> +  public posters: PosterList[];
: Poster[]

2020-08-24 06:27 UTC, vadimb commented on src/app/services/interceptor.service.ts
> +        const session = this.localStorage.getElement('session');
"Auth":

2020-08-24 06:29 UTC, vadimb commented on src/app/services/login.service.ts
> +            .pipe(
{
REQUIRES_AUTH,
}

2020-08-24 06:33 UTC, vadimb commented on src/app/services/login.service.ts
> +                        return error.stauts;
throw(new AuthError(sfsdfsdf sfsdfs));

2020-08-24 06:41 UTC, vadimb commented on src/app/services/movies.service.ts
> +                catchError((err) => throwError(err))
??????

2020-08-24 06:43 UTC, vadimb commented on src/app/services/movies.service.ts
> +                    .map((res) => ({ posterPath: `${imageUrl}${res}` }))
Merge

2021-05-13 15:32 UTC, closed without merging